



  
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

#pragma once


#include "C2S_common.h"

namespace C2S {


	class Proxy : public ::Proud::IRmiProxy
	{
	public:
	virtual bool Send_Req_Login ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Req_Login & req) PN_SEALED; 
	virtual bool Send_Req_Login ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Req_Login & req)   PN_SEALED;  
	virtual bool Send_Req_Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Req_Chat & req) PN_SEALED; 
	virtual bool Send_Req_Chat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Req_Chat & req)   PN_SEALED;  
static const PNTCHAR* RmiName_Send_Req_Login;
static const PNTCHAR* RmiName_Send_Req_Chat;
static const PNTCHAR* RmiName_First;
		Proxy()
		{
			if(m_signature != 1)
				::Proud::ShowUserMisuseError(::Proud::ProxyBadSignatureErrorText);
		}

		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; } 
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

}



