




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "C2S_proxy.h"

namespace C2S {


        
	bool Proxy::Send_Req_Login ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Req_Login & req)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Send_Req_Login;
__msg.Write(__msgid); 
	
__msg << req;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Send_Req_Login, (::Proud::RmiID)Rmi_Send_Req_Login);
	}

	bool Proxy::Send_Req_Login ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Req_Login & req)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Send_Req_Login;
__msg.Write(__msgid); 
	
__msg << req;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Send_Req_Login, (::Proud::RmiID)Rmi_Send_Req_Login);
	}
        
	bool Proxy::Send_Req_Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Req_Chat & req)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Send_Req_Chat;
__msg.Write(__msgid); 
	
__msg << req;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_Send_Req_Chat, (::Proud::RmiID)Rmi_Send_Req_Chat);
	}

	bool Proxy::Send_Req_Chat ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Req_Chat & req)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_Send_Req_Chat;
__msg.Write(__msgid); 
	
__msg << req;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_Send_Req_Chat, (::Proud::RmiID)Rmi_Send_Req_Chat);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Send_Req_Login =_PNT("Send_Req_Login");
#else
const PNTCHAR* Proxy::RmiName_Send_Req_Login =_PNT("");
#endif
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_Send_Req_Chat =_PNT("Send_Req_Chat");
#else
const PNTCHAR* Proxy::RmiName_Send_Req_Chat =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_Send_Req_Login;

}



