
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_common.h"
namespace S2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Recv_Rpy_Login,
               
		Rmi_Recv_Rpy_Chat,
               
		Rmi_Recv_Rpy_System_Chat,
	};

	int g_RmiIDListCount = 3;

}


